### PR TITLE
Changed URIs of Thing to be independent of Thing name.

### PR DESCRIPTION
**Pull request by ganesheth**
Changed ThingInterface to provide a list of URIs representing the Thing. These URIs can be added (optionally) when it is required to have URI something other than the name. For example, to have a structured URL, the thing might need an URL http://server/building_a/room_1/sensor_thing_x. If metadata does not contain explicit "hrefs" for thing then the URIs are constructed out of the name as before.

### CODE REVIEW

**Comment by mkovatsc** [comment]
Hi Ganesh
It looks like you want to "force" the URIs into a nice logical view of the system. While human-readable URIs are usually nice, since they make a system self-descriptive, they are often misused.

This nice logical view should come from the metadata in the TD.
The URI must be opaque for the client: It MUST NOT make any assumptions on its structure, and hence may not modify them or construct them in some way.

**Comment by ganesheth** [comment]
Hi Matthias,
I agree, the URI should not be used to convey heirarchy of things. However, still this change will allow keeping Thing name and uri separate. Right now the uri is formed directly from thing name. I think the Thing name can change, but the URI should remain same. For example the thing name could be "room_1_temperature" whereas the URI could based on some unique identifier for the sensor in the building.

**Comment by mkovatsc** [comment]
Okay, I see where this is headed. At this point, ThingWeb is a Gateway: it looks like the origin server to the client and maps/translates/converts internally as it wishes. Thus, I can also freely choose its resource structure and pick whatever it likes from the TD---as long as it is unique.

I see no benefit to hardcode this to the href field. Everything apart from the @type definitions can change in the TD, but can easily be propagated.

Side discussion:
With "as long as it is unique," we might have a problem: It is still unclear what the unique identifier is in the TD. Sure the href needs to be unique in the namespace of the thing. However, URIs should be transparent to the user. Currently the assumption is that "name" is unique. Yet it was said that it should be something human readable... In my opinion we need the @id, which is the value that needs to be passed to the Scripting API and is the unique ID inside the JSON-LD to cross-reference.

**Comment by ganesheth** [comment]
At the moment the URIs are harcoded to be formed from a binding specific prefix + thing name. I think this anyway needs to made flexible such that gateway code states  what it would like to use instead of thing name (which has no contractual guarantee about uniqueness or immutability).

Now, the question comes about what really identifies things and its interactions - clients and proxies might like to use the thing URI (and URI of each interaction in it). But URIs can be subject to change. On the other hand @id is something which can be constrained. So, coming back to the proposed change - it allows the URIs to be constructed without restricting it to name. If we decide to use the thing id as the suffix of the URI, then the proposed change still enables it.

**Comment by h0ru5** [comment]
From what I understood, the first commit adds functionality like: 

>   "when creating a thing via its TD, use the URIs given in the hrefs for the interactions. If there are none, use default URIs we have now for the relative URIs of the interactions."

Sounds useful for me, so I would gladly merge it in.

 However, could I ask you to open separate PRs for the later commits (the extended Metadata props, the complex types and the altered internal flow)?

small incremental merges make it easier to merge without breaking the demos and other stuff built on top of thingweb.

**Comment by ganesheth** [comment]
I am sorry, this happened because of my inexperience with Git. I have done many more changes in between. This time I will try to organize it into separate pulls, each with small changes.

**Comment by mkovatsc** [comment]
The plan forward is to continue working on the fork for the BACnet demonstrator. Once it is stable, I will integrate the changes manually into the ThingWeb code base and create manageable PRs from that.

**Pull request closed without merging**
